### ISSUE TITLE
Feature request: Round floating-point number to a certain number of digits

### ISSUE THREAD

**Issue by alt-graph** [gul-cpp/gul14#30]
Olaf proposed some kind of function to round a floating-point number to a certain number of digits.
As a rough idea, something like this:
```
double round_to_precision(double value, double precision)
{
    return (floor((value * pow(10, precision) + 0.5)) / pow(10, precision)); 
}
```

**Comment by Finii** [comment]
I'm not really sure that is at all possible (or useful).
Working with a fixed number of fractional digits is kind of contradictory to floating point.

But anyhow, I guess you mean `trunc` and not `floor`

**Comment by alt-graph** [comment]
It is certainly possible within the precision constraints of the floating-point number. But I am also not sure if it is widely useful. Let's keep the feature request around for some time, though. Olaf (or anyone else) can chime in if he needs this in many places.

**Comment by alt-graph** [comment]
Closing the feature request - no expression of interest from anywhere so far.
