### ISSUE TITLE
Compiler warning with SmallVector test

### ISSUE THREAD

**Issue by Finii** [gul-cpp/gul14#91]
Just dumping this here to not forget

![image](https://github.com/gul-cpp/gul14/assets/16012374/1bd256e5-e947-445a-beac-fb541fbb25c0)

**Comment by alt-graph** [comment]
Hmmm... I quickly debugged through the test, and it only calls `delete []` on memory that came from `new []`. So there seems to be no obvious smoking gun here, but maybe this needs a little more investigation.

**Comment by Finii** [comment]
Hmm, very strange, I can (reliably) trigger this warning if `libgul` is built and tested as subproject, but when I change directly into the subproject directory and set the build there up identical, the issue is not surfacing :thinking:   
Well, and it only happens if coverage is to be generated.

```shell
$ cd clientlib
$ meson setup build_gcov3 -Db_coverage=true --wrap=forcefallback --wipe -Dtine=disabled
$ ninja -C build_gcov3 test
```
